const {Wit, log} = require('node-wit');


module.exports = function (options) {

  if (!options || !options.accessToken) {
    throw new Error('No wit.ai Access Token specified');
  }

  options.minConfidence = options.minConfidence || 0.5;


  const client = new Wit({
    accessToken: options.accessToken,
    logger: new log.Logger(log.DEBUG) // optional
  });

  const middleware = {};

  middleware.receive = function (bot, message, next) {

    //Avoid text payload generated by buttons in Facebook Messenger
    if (message.text && message.text.indexOf("_") != -1 && !message.payload && !message.attachments) {
      client.message(message.text)
        .then((data) => {
        console.log('Wit.ai response: ' + JSON.stringify(data));
        message.intents = data.outcomes;
        next();
      })
        .catch((err) => {
        console.log(err);
        next(err);
        });
    } else {
      message.intents = [];
      next();
    }
  };

  middleware.hears = function (patterns, message) {
    if (message.intents && message.intents.length) {
      for (var i = 0; i < message.intents.length; i++) {
        for (var t = 0; t < patterns.length; t++) {
          if (message.intents[i].intent == patterns[t] && message.intents[i].confidence >= options) {
            return true;
          }
        }
      }
    }

    return false;
  };

  return middleware;
};
